version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: coco-boot:latest
    container_name: coco-boot
    # 映射端口
    ports:
      - "8181:8181"
    environment:
      # coco配置
      # 请求L站 state 过期时间 分钟
      COCO_EXPIRATION_TTL: "5"
      # L站 oauth2认证重定向地址
      COCO_REDIRECT_URI: ""
      # L站 oauth2认证客户端id
      COCO_CLIENT_ID: ""
      # L站 oauth2认证客户端secret
      COCO_CLIENT_SECRET: ""
      # L站 oauth2认证地址
      COCO_AUTHORIZATION_ENDPOINT: ""
      # L站 oauth2认证token地址
      COCO_TOKEN_ENDPOINT: ""
      # L站 oauth2认证用户信息地址
      COCO_USER_ENDPOINT: ""
      # 代理节点 完整地址
      COCO_BASE_API: ""
      # 代理节点
      COCO_BASE_PROXY: ""
      # ghu 频率秒  1秒8次
      COCO_FREQUENCY_TIME: "1"
      # ghu频率数
      COCO_FREQUENCY_DEGREE: "8"
      # 用户基础频率  1分钟10次
      COCO_USER_RATE_TIME: "1"
      # 用户基础频率数
      COCO_USER_FREQUENCY_DEGREE: "10"
      # 用户token 有效期无请求接口 小时
      COCO_USER_TOKEN_EXPIRE: "1"
      # 允许用户的最低等级等级
      COCO_USER_LEVEL: "2"
      # 风控参数
      # 一个账号 一天能获取多少次Token
      RISK_CONTR_GET_TOKEN_NUM: "10"
      # 单token 成功请求的最大数量 * 倍率 token失效
      RISK_CONTR_TOKEN_MAX_REQ: "500"
      # 每天用户最大请求数量 *倍率  限制 10小时 不可登陆
      RISK_CONTR_USER_MAX_REQ: "2000"
      RISK_CONTR_USER_MAX_TIME: "10"
      # 用户最大访问速率
      # 10次 该用户访问频率为  基础 * 0.5倍
      RISK_CONTR_TOKEN_INVALID_NUM: "10"
      # 30次  token失效  2小时不可登陆
      RISK_CONTR_REJECT_TIME_NUM: "30"
      RISK_CONTR_REJECT_TIME: "2"
      # ban 5次  5次不可登陆
      RISK_CONTR_BAN_NUM: "5"
      # redisson配置
      # redisson模式 single/cluster/sentinel 三选一 默认single
      # single 单机模式 cluster 集群模式 sentinel 哨兵模式
      REDISSON_MODE: "single"
      # redis数据库
      REDISSON_DATABASE: "0"
      # redis密码
      REDISSON_PASSWORD: ""
      # redisson单机地址 例如 redis://127.0.0.1:6379
      REDISSON_SINGLE_ADDRESS: ""
      # redisson集群节点 逗号分隔 例如 redis://127.0.0.1:7004,redis://127.0.0.1:7001,redis://127.0.0.1:7000
      REDISSON_CLUSTER_NODES: ""
      # redisson集群主连接池大小
      REDISSON_CLUSTER_MASTER_CONNECTION_POOL_SIZE: "64"
      # redisson集群重试次数
      REDISSON_CLUSTER_RETRY_ATTEMPTS: "3"
      # redisson集群重试间隔
      REDISSON_CLUSTER_RETRY_INTERVAL: "1500"
      # redisson集群扫描间隔
      REDISSON_CLUSTER_SCAN_INTERVAL: "1000"
      # redisson集群从连接池大小
      REDISSON_CLUSTER_SLAVE_CONNECTION_POOL_SIZE: "64"
      # redisson哨兵节点 逗号分隔 例如 redis://127.0.0.1:7004,redis://127.0.0.1:7001,redis://127.0.0.1:7000
      REDISSON_SENTINEL_NODES: ""
      # redisson哨兵主节点
      REDISSON_SENTINEL_MASTER: ""
      # redisson哨兵只写 主节点 true/false
      REDISSON_SENTINEL_MASTER_ONLY_WRITE: ""
      # redisson超时时间
      REDISSON_TIMEOUT: "3000"
      # redisson读模式 MASTER/SLAVE/MASTER_SLAVE 默认SLAVE 仅在集群模式下有效
      # SLAVE 从节点 MASTER 主节点 MASTER_SLAVE 主从混合
      REDISSON_READ_MODE: "SLAVE"
      # redisson订阅模式 MASTER/SLAVE 默认SLAVE 仅在集群模式下有效
      # SLAVE 从节点 MASTER 主节点
      REDISSON_SUBSCRIPTION_MODE: "SLAVE"
      # redisson连接池配置
      # redisson连接池连接超时时间 默认3000
      REDISSON_POOL_CONN_TIMEOUT: "3000"
      # redisson连接池最小空闲连接数 默认24
      REDISSON_POOL_MIN_IDLE: "24"
      # redisson连接池大小 默认64
      REDISSON_POOL_SIZE: "64"
      # redisson连接池读取超时时间 默认3000
      REDISSON_POOL_SO_TIMEOUT: "3000"


  redis:
    image: redis
    container_name: coco-redis
    environment:
      # 设置时区
      - TZ=Asia/Shanghai
    volumes: # 配置数据卷
      - ./redis_data:/data
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
